
    path('subscribers/', SubscriberListCreateView.as_view(), name='subscriber-list-create'),
    path('subscribers/<int:pk>/', SubscriberRetrieveUpdateDestroyView.as_view(), name='subscriber-detail'),
    path('budgets/', BudgetListCreateView.as_view(), name='budget-list-create'),
    path('budgets/<int:pk>/', BudgetRetrieveUpdateDestroyView.as_view(), name='budget-detail'),
    path('receipts/', ReceiptListCreateView.as_view(), name='receipt-list-create'),
    path('receipts/<int:pk>/', ReceiptRetrieveUpdateDestroyView.as_view(), name='receipt-detail'),



###
GET http://localhost:8000/workers/ HTTP/1.1
Content-Type: application/json

{
    "generator": "4",
    "password": "1111"
}
###
POST  http://localhost:8000/account/login/ HTTP/1.1
Content-Type: application/json

{
    "identifier": "ali",
    "password": "1111"
}