# Generated by Django 6.0.4 on 2026-04-09 21:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator_name', models.CharField(max_length=100, unique=True, verbose_name='اسم المولدة')),
                ('phone', models.CharField(help_text='07XXXXXXXXX', max_length=15, unique=True, verbose_name='رقم الهاتف')),
                ('password_hash', models.CharField(default='', max_length=256, verbose_name='كلمة المرور (مشفرة)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'حساب مولدة',
                'verbose_name_plural': 'حسابات المولدات',
                'ordering': ['generator_name'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المشترك')),
                ('circuit_number', models.CharField(max_length=20, verbose_name='رقم الجوزة')),
                ('ambers', models.PositiveIntegerField(verbose_name='الأمبيرات')),
                ('phone', models.CharField(blank=True, default='', max_length=15, verbose_name='رقم الهاتف')),
                ('date_subscribed', models.DateField(default=datetime.date.today, verbose_name='تاريخ الاشتراك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='mainapp.account', verbose_name='المولدة')),
            ],
            options={
                'verbose_name': 'مشترك',
                'verbose_name_plural': 'المشتركون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العامل')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='رقم الهاتف')),
                ('password_hash', models.CharField(max_length=256, verbose_name='كلمة المرور (مشفرة)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='mainapp.account', verbose_name='المولدة')),
            ],
            options={
                'verbose_name': 'عامل',
                'verbose_name_plural': 'العمال',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveIntegerField(verbose_name='الشهر')),
                ('amber_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر الأمبير (د.ع)')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='mainapp.account', verbose_name='المولدة')),
            ],
            options={
                'verbose_name': 'ميزانية',
                'verbose_name_plural': 'الميزانيات',
                'ordering': ['-year', '-month'],
                'unique_together': {('generator', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveIntegerField(verbose_name='الشهر')),
                ('amber_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الأمبير')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='صورة الإيصال')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('date_received', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='mainapp.account', verbose_name='المولدة')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='mainapp.subscriber', verbose_name='المشترك')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_receipts', to='mainapp.worker', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'إيصال',
                'verbose_name_plural': 'الإيصالات',
                'ordering': ['-date_received'],
                'unique_together': {('generator', 'subscriber', 'year', 'month')},
            },
        ),
    ]
