# Generated by Django 5.1.6 on 2025-07-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Subscriber Name')),
                ('circuit_number', models.CharField(max_length=50, unique=True)),
                ('Ambers', models.PositiveIntegerField(default=0, verbose_name='Ambers')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Worker Name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='Format: YYYY-MM', max_length=7, unique=True)),
                ('amber_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_subscribers', models.ManyToManyField(blank=True, related_name='budgets_paid', to='mainapp.subscriber')),
                ('unpaid_subscribers', models.ManyToManyField(blank=True, related_name='budgets_unpaid', to='mainapp.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('amber_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='mainapp.subscriber')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='mainapp.worker')),
            ],
        ),
    ]
