# Generated by Django 5.2.7 on 2025-11-14 10:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator_name', models.CharField(max_length=50, unique=True, verbose_name='Generator Name')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='User Name')),
                ('phone', models.CharField(help_text=' 077 xxx xxx xx', max_length=15, unique=True, verbose_name='Phone Number')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('is_worker', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Subscriber Name')),
                ('circuit_number', models.CharField(max_length=50, verbose_name='Circuit Number')),
                ('Ambers', models.PositiveIntegerField(verbose_name='Ambers')),
                ('phone', models.CharField(default='000', help_text=' 077 xxx xxx xx', max_length=15, verbose_name='Phone Number')),
                ('barcode_image', models.ImageField(upload_to='subscribers_barcodes/', verbose_name='Barcode Image')),
                ('date_subscribed', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Subscribed')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='mainapp.account', verbose_name='Electric Generator Account')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_uuid', models.CharField(help_text='Format: generatorname-YYYY-MM-receiptid', max_length=11, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('amber_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='mainapp.account', verbose_name='Electric Generator Account')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='mainapp.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_uuid', models.CharField(auto_created=True, help_text='Format: generator-YYYY-MM', max_length=7, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('amber_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='mainapp.account', verbose_name='Electric Generator Account')),
                ('paid_subscribers', models.ManyToManyField(blank=True, related_name='budgets_paid', to='mainapp.subscriber')),
                ('unpaid_subscribers', models.ManyToManyField(blank=True, related_name='budgets_unpaid', to='mainapp.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='User Name')),
                ('phone', models.CharField(help_text=' 077 xxx xxx xx', max_length=15, verbose_name='Phone Number')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='mainapp.account', verbose_name='Electric Generator Account')),
            ],
        ),
    ]
