# Generated by Django 5.1.6 on 2025-07-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='year_month_subscriber_id',
            field=models.CharField(help_text='Format: YYYY-MM-ID', max_length=11, unique=True),
        ),
    ]
