# Generated by Django 5.1.6 on 2025-08-27 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='date',
        ),
        migrations.AddField(
            model_name='budget',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='date_received',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='date_subscribed',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date Subscribed'),
        ),
        migrations.AddField(
            model_name='worker',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
