# Generated by Django 5.2.7 on 2025-11-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='year_month_subscriber_id',
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_id',
            field=models.CharField(default=1, help_text='Format: generatorname-YYYY-MM-receiptid', max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electricgeneratormodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Generator Name'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Subscriber Name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Worker Name'),
        ),
    ]
