# Generated by Django 5.2.7 on 2025-11-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_receipt_year_month_subscriber_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='barcode_data',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='barcode_image',
            field=models.ImageField(default=1, upload_to='subscribers/', verbose_name='Barcode Image'),
            preserve_default=False,
        ),
    ]
