# Generated by Django 5.1.6 on 2025-07-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_receipt_year_month_subscriber_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='unpaid_subscribers',
        ),
    ]
