# Generated by Django 5.1.6 on 2025-08-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_budget_unpaid_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='barcode_data',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Barcode Data'),
        ),
    ]
